meta_product_name: "El Man De Los Chorizos"
meta_title: "Home made Chorizos in Paris | @ElManDeLosChorizos"
meta_description: "An unique recipe of chorizos in Paris."
meta_image: "choriLogo.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
